program InventoryJKT;

uses
  Forms,
  MAIN in 'MAIN.pas' {frmMenu},
  ufrmCxBrowse in 'ufrmCxBrowse.pas' {frmCxBrowse},
  UfrmLogin in 'UfrmLogin.pas' {frmLogin},
  ufrmUser in 'ufrmUser.pas' {frmUser},
  uFrmbantuan in 'bantu\uFrmbantuan.pas' {frmBantuan},
  Ulib in 'bantu\Ulib.pas',
  uModuleConnection in 'bantu\uModuleConnection.pas',
  uReport in 'bantu\uReport.pas',
  ufrmBrowseGudang in 'ufrmBrowseGudang.pas' {frmBrowseGudang},
  ufrmGudang in 'ufrmGudang.pas' {frmGudang},
  ufrmBrowseCostCenter in 'ufrmBrowseCostCenter.pas' {frmBrowseCostCenter},
  ufrmCostCenter in 'ufrmCostCenter.pas' {frmCostCenter},
  ufrmBrowseSalesman in 'ufrmBrowseSalesman.pas' {frmBrowseSalesman},
  ufrmSalesman in 'ufrmSalesman.pas' {frmSalesman},
  ufrmBrowseCustomer in 'ufrmBrowseCustomer.pas' {frmBrowseCustomer},
  ufrmCustomer in 'ufrmCustomer.pas' {frmCustomer},
  ufrmBrowseSupplier in 'ufrmBrowseSupplier.pas' {frmBrowseSupplier},
  ufrmSupplier in 'ufrmSupplier.pas' {frmSupplier},
  ufrmBrowseJC in 'ufrmBrowseJC.pas' {frmBrowseJC},
  ufrmJC in 'ufrmJC.pas' {frmJC},
  ufrmBrowseSubBarang in 'ufrmBrowseSubBarang.pas' {frmBrowseSubBarang},
  ufrmSubBarang in 'ufrmSubBarang.pas' {frmSubBarang},
  ufrmPesanan in 'ufrmPesanan.pas' {frmPesanan},
  ufrmBrowseBarang in 'ufrmBrowseBarang.pas' {frmBrowseBarang},
  ufrmBarang in 'ufrmBarang.pas' {frmBarang},
  ufrmBrowsePesanan in 'ufrmBrowsePesanan.pas' {frmBrowsePesanan},
  ufrmBrowsePO in 'ufrmBrowsePO.pas' {frmBrowsePO},
  ufrmPO in 'ufrmPO.pas' {frmPO},
  ufrmBrowseBPB in 'ufrmBrowseBPB.pas' {frmBrowseBPB},
  ufrmBPB in 'ufrmBPB.pas' {frmBPB},
  ufrmInvoice in 'ufrmInvoice.pas' {frmInvoice},
  ufrmBrowseInvoice in 'ufrmBrowseInvoice.pas' {frmBrowseInvoice},
  ufrmBrowseMutasiGudang in 'ufrmBrowseMutasiGudang.pas' {frmBrowseMutasiGudang},
  ufrmMutasiGudang in 'ufrmMutasiGudang.pas' {frmMutasiGudang},
  ufrmBayarSupplier in 'ufrmBayarSupplier.pas' {frmBayarSupplier},
  ufrmBrowseMutasiCabang in 'ufrmBrowseMutasiCabang.pas' {frmBrowseMutasiCabang},
  ufrmMutasiCabang in 'ufrmMutasiCabang.pas' {frmMutasiCabang},
  ufrmBrowseReturBeli in 'ufrmBrowseReturBeli.pas' {frmBrowseReturBeli},
  ufrmReturBeli in 'ufrmReturBeli.pas' {frmReturBeli},
  ufrmBrowseMutasiCabang2 in 'ufrmBrowseMutasiCabang2.pas' {frmBrowseMutasiCabang2},
  ufrmMutasiCabang2 in 'ufrmMutasiCabang2.pas' {frmMutasiCabang2},
  ufrmDO in 'ufrmDO.pas' {frmDO},
  ufrmBrowseDO in 'ufrmBrowseDO.pas' {frmBrowseDO},
  ufrmBrowseFP in 'ufrmBrowseFP.pas' {frmBrowseFP},
  ufrmFP in 'ufrmFP.pas' {frmFP},
  ufrmFeeCustomer in 'ufrmFeeCustomer.pas' {frmFeeCustomer},
  ufrmBrowseFeeCustomer in 'ufrmBrowseFeeCustomer.pas' {frmBrowseFeeCustomer},
  ufrmBayarCustomer in 'ufrmBayarCustomer.pas' {frmBayarCustomer},
  ufrmBrowseReturJual in 'ufrmBrowseReturJual.pas' {frmBrowseReturJual},
  ufrmReturJual in 'ufrmReturJual.pas' {frmReturJual},
  ufrmPenerimaanLain in 'ufrmPenerimaanLain.pas' {frmPenerimaanLain},
  ufrmPembayaranLain in 'ufrmPembayaranLain.pas' {frmPembayaranLain},
  ufrmBrowsePenerimaanLain in 'ufrmBrowsePenerimaanLain.pas' {frmBrowsePenerimaanLain},
  ufrmBrowsePembayaranLain in 'ufrmBrowsePembayaranLain.pas' {frmBrowsePembayaranLain},
  ufrmHitungStok in 'ufrmHitungStok.pas' {frmHitungStok},
  ufrmBrowseHitungStok in 'ufrmBrowseHitungStok.pas' {frmBrowseHitungStok},
  ufrmBrowseBayarCustomer in 'ufrmBrowseBayarCustomer.pas' {frmBrowseBayarCustomer},
  ufrmListJual in 'ufrmListJual.pas' {frmListJual},
  ufrmBrowseKoreksiStok in 'ufrmBrowseKoreksiStok.pas' {frmBrowseKoreksiStok},
  ufrmKoreksiStok in 'ufrmKoreksiStok.pas' {frmKoreksiStok},
  ufrmLapPersediaan in 'ufrmLapPersediaan.pas' {frmLapPersediaan},
  ufrmListJualvsTarget in 'ufrmListJualvsTarget.pas' {frmListJualvsTarget},
  ufrmListFOS in 'ufrmListFOS.pas' {frmListFOS},
  ufrmListJual2 in 'ufrmListJual2.pas' {frmListJual2},
  ufrmListJual3 in 'ufrmListJual3.pas' {frmListJual3},
  ufrmListJual4 in 'ufrmListJual4.pas' {frmListJual4},
  ufrmListInkaso in 'ufrmListInkaso.pas' {frmListInkaso},
  ufrmListMutasiStok in 'ufrmListMutasiStok.pas' {frmListMutasiStok},
  ufrmListJual5 in 'ufrmListJual5.pas' {frmListJual5},
  ufrmBrowseFPBayangan in 'ufrmBrowseFPBayangan.pas' {frmBrowseFPBayangan},
  ufrmFPBayangan in 'ufrmFPBayangan.pas' {frmFPBayangan},
  ufrmListKas in 'ufrmListKas.pas' {frmListKas},
  ufrmBrowseFakturPajak in 'ufrmBrowseFakturPajak.pas' {frmBrowseFakturPajak},
  ufrmFakturPajak in 'ufrmFakturPajak.pas' {frmFakturPajak},
  ufrmBrowseJurnalUmum in 'ufrmBrowseJurnalUmum.pas' {frmBrowseJurnalUmum},
  ufrmJurnalUmum in 'ufrmJurnalUmum.pas' {frmJurnalUmum},
  uFrmLihatGambar in 'bantu\uFrmLihatGambar.pas' {frmLihatGambar},
  ufrmBrowseJurnal in 'ufrmBrowseJurnal.pas' {frmBrowseJurnal},
  ufrmPerusahaan in 'ufrmPerusahaan.pas' {frmPerusahaan},
  ufrmLapBulanan in 'ufrmLapBulanan.pas' {frmLapBulanan},
  ufrmLapYTD in 'ufrmLapYTD.pas' {frmLapYTD},
  ufrmBrowseHistoryHargaJual in 'ufrmBrowseHistoryHargaJual.pas' {frmBrowseHistoryHargaJual},
  ufrmLapBulananInkaso in 'ufrmLapBulananInkaso.pas' {frmLapBulananInkaso},
  ufrmBrowseKartuStok in 'ufrmBrowseKartuStok.pas' {frmBrowseKartuStok},
  ufrmListTransaksiHarian in 'ufrmListTransaksiHarian.pas' {frmListTransaksiHarian},
  ufrmBrowsePencairanGiro in 'ufrmBrowsePencairanGiro.pas' {frmBrowsePencairanGiro},
  ufrmListTransaksiHarian2 in 'ufrmListTransaksiHarian2.pas' {frmListTransaksiHarian2},
  ufrmPencairanGiro in 'ufrmPencairanGiro.pas' {frmPencairanGiro},
  ufrmLapBulanan2 in 'ufrmLapBulanan2.pas' {frmLapBulanan2},
  ufrmListSaldoPiutang in 'ufrmListSaldoPiutang.pas' {frmListSaldoPiutang},
  ufrmListMutasiStok2 in 'ufrmListMutasiStok2.pas' {frmListMutasiStok2},
  ufrmListItemMinus in 'ufrmListItemMinus.pas' {frmListItemMinus},
  ufrmEditJT in 'ufrmEditJT.pas' {frmEditJT},
  ufrmBrowseStokExpired in 'ufrmBrowseStokExpired.pas' {frmBrowseStokExpired},
  ufrmBayarBiayaPromosi in 'ufrmBayarBiayaPromosi.pas' {frmBayarBiayaPromosi},
  ufrmBrowseBayarBiayaPromosi in 'ufrmBrowseBayarBiayaPromosi.pas' {frmBrowseBayarBiayaPromosi},
  ufrmLapStokItemTerlaris in 'ufrmLapStokItemTerlaris.pas' {frmLapStokItemterlaris},
  ufrmSalesMarketing in 'ufrmSalesMarketing.pas' {frmSalesMarketing},
  ufrmSettingKomisi in 'ufrmSettingKomisi.pas' {frmSettingKomisi},
  ufrmKomisiMarketing in 'ufrmKomisiMarketing.pas' {frmKomisiMarketing},
  ufrmSettingKomisi2 in 'ufrmSettingKomisi2.pas' {frmSettingKomisi2},
  ufrmKomisiSalesman in 'ufrmKomisiSalesman.pas' {frmKomisisalesman},
  ufrmListKas2 in 'ufrmListKas2.pas' {frmListKas2},
  ufrmtutupperiode in 'ufrmtutupperiode.pas' {frmTutupPeriode},
  ufrmBrowseMusnah in 'ufrmBrowseMusnah.pas' {frmBrowseMusnah},
  ufrmMusnah in 'ufrmMusnah.pas' {frmMusnah},
  ufrmCetak in 'ufrmCetak.pas' {frmCetak},
  ufrmBrowseSerahTerimaFaktur in 'ufrmBrowseSerahTerimaFaktur.pas' {frmBrowseSerahTerimaFaktur},
  ufrmSerahTerimaFaktur in 'ufrmSerahTerimaFaktur.pas' {frmSerahTerimaFaktur},
  ufrmBrowseSetingBiayaPromosi in 'ufrmBrowseSetingBiayaPromosi.pas' {frmBrowseSetingBiayaPromosi},
  ufrmSetingBiayaPromosi in 'ufrmSetingBiayaPromosi.pas' {frmSetingBiayaPromosi},
  ufrmLapBulanan3 in 'ufrmLapBulanan3.pas' {frmLapBulanan3},
  ufrmLapPencapaianSales in 'ufrmLapPencapaianSales.pas' {frmLapPencapaianSales},
  ufrmProsesBiayaPromosi in 'ufrmProsesBiayaPromosi.pas' {frmProsesBiayaPromosi},
  ufrmBrowseJurnal2 in 'ufrmBrowsejurnal2.pas' {frmBrowseJurnal2},
  ufrmEstimasiSales in 'ufrmEstimasiSales.pas' {frmEstimasiSales},
  ufrmBrowseEstimasiSales in 'ufrmBrowseEstimasiSales.pas' {frmBrowseEstimasiSales},
  UfrmOtorisasi in 'UfrmOtorisasi.pas' {frmOtorisasi},
  ufrmBrowseBayarSupplier in 'ufrmBrowseBayarSupplier.pas' {frmBrowseBayarSupplier},
  ufrmListIOS in 'ufrmListIOS.pas' {frmListIOS},
  ufrmBrowseTandaTerima in 'ufrmBrowseTandaTerima.pas' {frmBrowseTandaTerima},
  ufrmTandaTerima in 'ufrmTandaTerima.pas' {frmTandaTerima},
  ufrmPostingJurnalBulanan in 'ufrmPostingJurnalBulanan.pas' {frmPostingJurnalBulanan},
  ufrmLapBiayaBulanan in 'ufrmLapBiayaBulanan.pas' {frmLapBiayaBulanan},
  ufrmProsesGaji in 'ufrmProsesGaji.pas' {frmProsesGaji},
  ufrmFakturPajak2 in 'ufrmFakturPajak2.pas' {frmFakturPajak2},
  ufrmLapLabaRugi in 'ufrmLapLabaRugi.pas' {frmLapLabaRugi},
  ufrmLapNeraca in 'ufrmLapNeraca.pas' {frmLapNeraca},
  uFrmbantuan2 in 'bantu\uFrmbantuan2.pas' {frmBantuan2},
  ufrmProsesAvgcost in 'ufrmProsesAvgcost.pas' {frmProsesAvgcost},
  ufrmSubBarangPF in 'ufrmSubBarangPF.pas' {frmSubBarangPF},
  ufrmBrowseSubBarangPF in 'ufrmBrowseSubBarangPF.pas' {frmBrowseSubBarangPF},
  ufrmBrowseSetingBarangPF in 'ufrmBrowseSetingbarangpf.pas' {frmBrowseSetingBarangPF},
  ufrmSetingBarangPF in 'ufrmSetingBarangPF.pas' {frmSetingBarangPF},
  ufrmLapKunjunganMarketing in 'ufrmLapKunjunganMarketing.pas' {frmLapKunjunganMarketing},
  ufrmLapBulanan4 in 'ufrmLapBulanan4.pas' {frmLapBulanan4},
  ufrmLapLabaRugi2 in 'ufrmLaplabarugi2.pas' {frmLapLabaRugi2},
  ufrmFakturPajak3 in 'ufrmFakturPajak3.pas' {frmFakturPajak3};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TfrmMenu, frmMenu);
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.Run;
    end.
